### ISSUE TITLE
Dungeon Quests wont Clear

### ISSUE THREAD

**Issue by Luce3f4** [DexterHuang/CyberCodeOnline#824]
I've cleared the dungeon quest but it wont register. Tried refreshing, closing and opening game, logout/login. Doesnt work. Same happened for others too.

**Comment by AuroraEndante** [comment]
Just got the same issue on mobile, except I'm also stuck in the wrong room of the dungeon for some reason. Finished off the tough challenge boss and when it died the screen showed me the start room instead of the boss room.

![game 2021-05-26](https://user-images.githubusercontent.com/84821313/119737904-cd3cb880-be4d-11eb-8922-1d8958cc4bb8.jpg)

**Comment by DexterHuang** [comment]
this should be fixed :)
