### ISSUE TITLE
Suggestion: Change cache drop rates

### ISSUE THREAD

**Issue by jeremy-j-ackso** [DexterHuang/CyberCodeOnline#90]
Currently it seems that caches are common enough that it seems like things aren't selling in the Player Market even when they're priced far below what it costs to print a cache of that rarity.

**Comment by DexterHuang** [comment]
yeah, I noticed that too, do you mean we should lower the drop rate for rarer caches?

**Comment by jeremy-j-ackso** [comment]
Probably would want others to weigh in on this since it'll probably have a big impact, but yes. Lowering the drop rate for HQ and Rare caches will make those and HQ and Rare equipment more viable in the markets, and hopefully prop up the price. I've found that trying to sell HQ stuff is pretty pointless now, so I just scrap it. I still sell Rare stuff, but it's hard to get more than ~1000BTC for it in lvs20-30-ish.

I'm not sure what to do about Legendary caches though. Lots of players seem to be using the market as storage for Legendary caches by putting the highest price possible on them. It's their choice and it's still theoretically possible somebody could buy them, so it's fine, but it's also not what I perceive the intent of the market to be: it should be for selling, not storage. But Legendary equipment seems to sell pretty easily for 3000BTC-5000BTC between lvs20-30.

Maybe another side-idea to complement this: have the price to print caches scale with level? That could potentially encourage more lower-level Rare and Legendary items, creating a market for them, and potentially making Legendary cache hoarding less desirable?

**Comment by DexterHuang** [comment]
You are right, there should be some rework for the pricing and printing mechanic, 
I think I could scale the price base on item level, but allows players to choose the level they want to print for

**Comment by tinamilford** [comment]
Allowing players to choose level to print for would also allow for people playing with friends to print and sell lower level gear for friends not at the same level. This idea is cool.

**Comment by robbyt1414** [comment]
The storage in market can be solved by simply allowing people to place a bid on item. If the item is not brought out within 7 days highest bid takes it.  You could also have a minimum base this could be 2x the instant price of the instant market.  Exp i put legendary cache on 50k someome puts 30k bid.  Now if No one takes it within the 7 days the 30k bid wins. This would also make the market prices development with supply and demand. People might say but if no one bids i only get 2x value . but on the other hand you have placed on the market because you don't need it or need the space so x2, highest bid or brought outright for what you placed it as is all a bonus. I also think an increase in market slots would give a boost to the market. Maybe increase by level or buying extra slots or a new skill that improves market slots based on market activity

**Comment by tripplehelix** [comment]
This was in discord, Dex mentioned that printing for lower levels may remove the need for lower levels to craft.
